{
    "name": "Add Car To Product",
    "version": "1.0.0",
    "summary": "Enhance vehicle and product compatibility",
    "description": "Manages vehicle compatibility for products and vehicles.",
    "category": "Custom",
    "author": "Stepan Oleksiuk",
    "depends": ["base", "fleet", "product"],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/product_menu_views.xml",
        # "views/product_product_view.xml",
        "views/product_template_views.xml",
        "views/product_autopart_fields_view.xml",
        "views/fleet_vehicle_model_views.xml",
        "views/compatible_vehicle_ids_views.xml",
        "views/website_product_vehicle_filter.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
